### ISSUE TITLE
SAMJ model installation fails on Apple Silicone Macs: Micromamba unable to install mkl

### ISSUE THREAD

**Issue by microscope** [segment-anything-models-java/SAMJ-IJ#18]
Trying to install SAMJ-IJ plugin on an M2 Apple MacBook Pro running macOS Sonoma 14.4.1:
- First installed and updated Fiji (ImageJ2 Version 2.14.0/1.54i) and restarted
- Then installed SAMJ plugin via Manage Update Sites ... and restarted
- Fiji:Plugins > SAMJ > SAMJ Annotator started up
- Installation of model EfficientViTSAM-xl1 fails (red message "This model is not installed yet." reappears) with this Console message:

java.lang.RuntimeException: Error executing the following command: [/Applications/Fiji.app/appose_x86_64/bin/micromamba, create, -p, /Applications/Fiji.app/appose_x86_64/envs/efficientvit_sam_env, -c, conda-forge, python=3.11, -c, pytorch, libpng, libjpeg-turbo, scikit-image, pytorch=2.0.1, torchvision=0.15.2, cpuonly, mkl=2024.0.0, cmake, onnx, onnxruntime, timm=0.6.13, --yes]
22:43:05 -- STARTING INSTALLATION

22:43:24 -- TERMINATED PROCESS
670a93a8-bea6-45fb-8cfc-6b34fbbcbc30error    libmamba Could not solve for environment specs
670a93a8-bea6-45fb-8cfc-6b34fbbcbc30The following package could not be installed
670a93a8-bea6-45fb-8cfc-6b34fbbcbc30└─ mkl 2024.0.0**  does not exist (perhaps a typo or a missing channel).
670a93a8-bea6-45fb-8cfc-6b34fbbcbc30critical libmamba Could not solve for environment specs
	at io.bioimage.modelrunner.apposed.appose.Mamba.runMamba(Mamba.java:1177)
	at io.bioimage.modelrunner.apposed.appose.Mamba.runMamba(Mamba.java:1199)
	at io.bioimage.modelrunner.apposed.appose.Mamba.create(Mamba.java:655)
	at ai.nets.samj.SamEnvManager.installEfficientViTSAMPython(SamEnvManager.java:639)
	at ai.nets.samj.SamEnvManager.installEfficientViTSAMPython(SamEnvManager.java:613)
	at ai.nets.samj.SamEnvManager.installEfficientViTSAM(SamEnvManager.java:1045)
	at ai.nets.samj.gui.SAMModelPanel.lambda$createInstallationThread$7(SAMModelPanel.java:321)
	at java.lang.Thread.run(Thread.java:750)

- Same problem with model EfficientViTSAM-I0
- Same problem on coworkers silicone MacBook running macOS Ventura
- No problem whatsoever installing and running SAMJ on Intel MacBook Pro running macOS Monterey (12.7.2) -- works great!

**Looks like the problem lies with micromamba being unable to install mkl, the Intel® oneAPI Math Kernel Library.**

I am not a Java, Python, or Mamba expert, so I am stumped what to try to resolve the issue and would be grateful for any suggestions.

Thanks,

microscope

**Comment by carlosuc3m** [comment]
hello @microscope , first of all thank you for trying to use SAMJ and thank you for the debug effort that you made.
Yesss, I will release today or tomorrow a version that does not use mkl for apple silicon!

I will let you know once is out.
Also what do you mean by a repository for developers?

Regards,
carlos

**Comment by carlosuc3m** [comment]
Hello @microscope 
First of all sorry for the delay, but now you should be able to use SAMJ in your Apple Silicon laptop.

The repo that contains the backend of the plugin is here:
https://github.com/segment-anything-models-java/SAMJ
Sorry there is still not much documentation. We call it developers repo because there is the code used for the backend of SAMJ. SAMJ consists on a Java-python backend that runs SAM and functionalities based on SAM (SAM segmentation coming soon!) and this repo is the IJ/Fiji specific repository that acts as the front end.


The idea is that every Java based software could use the same SAMJ backend.

Thanks a lot for your interest.

If the plugin works let me know and I will close this issue.
Regards,
Carlos

**Comment by carlosuc3m** [comment]
Forgot to tell that you need to update the plugin in the update site

**Comment by carlosuc3m** [comment]
Awesome!! I am happy to hear that it works!

Thanks a lot for hte help. I am closing this issue, but please do not hesitate to open other issues if you want to ask something or report any other problem.

Carlos
