### ISSUE TITLE
SAMJ is not available from update sites

### ISSUE THREAD

**Issue by ashirini** [segment-anything-models-java/SAMJ-IJ#2]
Hi,
I am trying to install SAMJ, but it is not available from the list of update sites.
![Picture1](https://github.com/segment-anything-models-java/SAMJ-IJ/assets/152455564/7d36abe6-6f75-48cb-b317-c58225a300db)

**Comment by cfusterbarcelo** [comment]
Hello!

Thank you for showing interest in SAMJ. Indeed, the plugin isn't available on the update site yet, as we haven't officially released it. It's slated for release in the upcoming weeks. The documentation you encountered was only a preliminary version.
Thank you again for your interest!
