### ISSUE TITLE
plugin stopped to accept tif files after update to 0.0.2

### ISSUE THREAD

**Issue by pawlowska** [segment-anything-models-java/SAMJ-IJ#27]
I successfully used SAMJ 0.0.1 on several different datasets. After update to 0.0.2, I am getting an error "Make sure the image used is 2D 1 or 3 channels". The image is cropped from a multidimensional one, so there might be some traces in metadata, but it was resaved as 2D 1ch crop. SAMJ 0.0.01 that I have on another machine still reads the file. I tested on 2 or 3 different datasets. 

<img width="983" alt="SAMJ002 fails" src="https://github.com/user-attachments/assets/4bb5649c-e078-4f41-af03-2a2842235b8c">
<img width="1057" alt="SAMJ001 works" src="https://github.com/user-attachments/assets/97218147-439a-404d-b7ad-5ff9fe026ca4">

[RNAscope_crop.zip](https://github.com/user-attachments/files/17325159/RNAscope_crop.zip)

**Comment by WCH-Jason** [comment]
I had the same problem!

**Comment by carlosuc3m** [comment]
WE are dealing with some bugs sorry! It will be back to normal soon!
Are you using windows, mac or linux?
@pawlowska @WCH-Jason

**Comment by WCH-Jason** [comment]
windows



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/11/2024 17:29 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [segment-anything-models-java/SAMJ-IJ] plugin stopped to accept tif files after update to 0.0.2 (Issue #27) |

WE are dealing with some bugs sorry! It will be back to normal soon!
Are you using windows, mac or linux?
@***@***.***

**Comment by carlosuc3m** [comment]
Hello again @pawlowska and @WCH-Jason 
I have updated the SAMJ version in Fiji, could you please update it and try if it is working?
In the updated version SAM2 Tiny is the first model on the left.
Sorry for the inconvenience and thanks for your patience!
Regards,
Carlos

**Comment by carlosuc3m** [comment]
Also just so you know, the new plugin implements crtl+Z for undo and ctrl+Y for redo

**Comment by carlosuc3m** [comment]
The last update seems to work on my windows machine

**Comment by pawlowska** [comment]
@carlosuc3m the update helped for me, thank you!
