### ISSUE TITLE
Error installing EfficientSAM

### ISSUE THREAD

**Issue by NGSchulz** [segment-anything-models-java/SAMJ-IJ#9]
I was able to install the SAMJ plugin with no problems, but haven't been able to install the models. When trying, the process is immediately terminated and kicks back this error: 

> java.lang.RuntimeException: Error executing the following command: [cmd.exe, /c, C:\Program Files\Fiji.app\appose_x86_64\Library\bin\micromamba.exe, create, -p, C:\Program Files\Fiji.app\appose_x86_64\envs\sam_common_env, -c, conda-forge, python=3.11, -c, pytorch, libpng, libjpeg-turbo, scikit-image, pytorch=2.0.1, torchvision=0.15.2, cpuonly, --yes]
> 15:51:26 -- STARTING INSTALLATION
> 
> 15:51:26 -- TERMINATED PROCESS
> 06093d9d-e54b-49f5-a0e2-968f928efb4f'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> 	at io.bioimage.modelrunner.apposed.appose.Mamba.runMamba(Mamba.java:1145)
> 	at io.bioimage.modelrunner.apposed.appose.Mamba.runMamba(Mamba.java:1167)
> 	at io.bioimage.modelrunner.apposed.appose.Mamba.create(Mamba.java:653)
> 	at ai.nets.samj.SamEnvManager.installEfficientSAMPython(SamEnvManager.java:570)
> 	at ai.nets.samj.SamEnvManager.installEfficientSAMPython(SamEnvManager.java:544)
> 	at ai.nets.samj.SamEnvManager.installEfficientSAMSmall(SamEnvManager.java:1000)
> 	at ai.nets.samj.gui.SAMModelPanel.lambda$createInstallationThread$7(SAMModelPanel.java:311)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by xulman** [comment]
Hi,
I think the issue has its root in the fact that the path, into which you have installed your Fiji, that the path includes whitespace: `Program Files`.

The quickest fix I expect to be to place your Fiji (the one with SAMJ) into some more "normal" path, e.g. `C:\work\project\Fiji_withSAMJ.app`. Notice that one can rename the folder with Fiji and have more Fijis side by side...

----
I would recommend to avoid placing Fiji into Desktop or Downloads folders, or various other places that Windows likes to translate too and that work under multiple paths/names. On the other hand, I'm seeing colleagues having Fiji on the Windows desktops without any problems.

Finally, Windows for some security reasons, I believe, somehow controls writing into the `Program Files` folder, which [could prohibit for example Fiji updater to work well.](https://imagej.net/software/fiji/downloads#installation)

**Comment by carlosuc3m** [comment]
Very good catch @xulman !!! I will implement a fix over the weekend! Thanks for your collaboration @NGSchulz

**Comment by NGSchulz** [comment]
Thank you both! I was able to download the models after moving the folder and updating SAMJ

**Comment by ofrag** [comment]
I also encounter problems installing EfficientSAM. 
My Fiji is NOT installed under C:\ProgramFiles, and I get another error: 
```
 Exception in thread "Thread-19" java.lang.NoSuchMethodError: io.bioimage.modelrunner.engine.installation.FileDownloader.call(Ljava/lang/Thread;)V
	at io.bioimage.modelrunner.apposed.appose.Mamba.lambda$downloadMicromamba$0(Mamba.java:379)
	at java.lang.Thread.run(Thread.java:750)
java.io.IOException: Error downloading micromamba from: https://micro.mamba.pm/api/micromamba/win-64/latest
	at io.bioimage.modelrunner.apposed.appose.Mamba.downloadMicromamba(Mamba.java:388)
	at io.bioimage.modelrunner.apposed.appose.Mamba.installMicromamba(Mamba.java:424)
	at ai.nets.samj.SamEnvManager.installMambaPython(SamEnvManager.java:951)
	at ai.nets.samj.SamEnvManager.installEfficientSAMSmall(SamEnvManager.java:998)
	at ai.nets.samj.gui.SAMModelPanel.lambda$createInstallationThread$7(SAMModelPanel.java:311)
	at java.lang.Thread.run(Thread.java:750)

```
any hint would be appreciated. 
Can it be related to Firewall ?

**Comment by carlosuc3m** [comment]
Hello @ofrag , could you check if you have just one `dl-modelrunner` JAR file inside the `jars` folder of Fiji.
If you have more than one just keep the one with version 0.5.5 and if you have none or you do not have version 0.5.5, please update Fiji.

If that does not fix it, could you give more details about you machine and installation?
Regards,
Carlos

**Comment by ofrag** [comment]
Great catch @carlosuc3m !
Indeed I had two versions of `dl-modelrunner` . deleting the old version solved the model download issue. 

However, trying to use SAMJ for annotation failed. in the `Go!` stage :
- I use a small image 288*302 pixels , and the small model - `EfficientViTSAM-I0` . 
- The Go! step takes forever and I get the following in the console window:
`Start the encoding
task.update('start')
import numpy as np
from skimage import measure
measure.label(np.ones((10, 10)), connectivity=1)
import torch
import sys
import os
os.chdir(r'C:\Fiji\Fiji.app\appose_x86_64\envs\efficientvit_sam_env\efficientvit')
from multiprocessing import shared_memory
task.update('import sam')
from efficientvit.models.efficientvit import EfficientViTSam, efficientvit_sam_l0
from efficientvit.models.efficientvit.sam import EfficientViTSamPredictor
task.update('imported')

model = efficientvit_sam_l0().cpu().eval()
eps = 1e-6
for m in model.modules():
  if isinstance(m, (torch.nn.GroupNorm, torch.nn.LayerNorm, torch.nn.modules.batchnorm._BatchNorm)):
    if eps is not None:
      m.eps = eps
f_name = os.path.realpath(os.path.expanduser(r'C:\Fiji\Fiji.app\appose_x86_64\envs\efficientvit_sam_env\efficientvit\weights\l0.pt'))
weight = torch.load(f_name, map_location='cpu')
if "state_dict" in weight:
  weight = weight["state_dict"]
model.load_state_dict(weight)
predictor = EfficientViTSamPredictor(model)
task.update('created predictor')
globals()['shared_memory'] = shared_memory
globals()['measure'] = measure
globals()['np'] = np
globals()['torch'] = torch
globals()['predictor'] = predictor
def is_edge_pixel(image, cx,cy):
    # assuming image[cy,cx] != 0
    h,w = image.shape
    if cx < 0 or cx >= w or cy < 0 or cy >= h:
        return False
    # NB: cx,cy are valid coords
    return cy == 0 or image[cy-1,cx] == 0 or cx == 0 or image[cy,cx-1] == 0 or cx == w-1 or image[cy,cx+1] == 0 or cy == h-1 or image[cy+1,cx] == 0

def find_contour_neighbors(image, cx,cy, last_forward_dir):
    ccw_dir = [8,9,6,3,2,1,4,7] # "numpad directions"
    # so, directions are coded, and numbers 1-4,6-9 are used,
    # let's use them as indices to the arrays below:
    dir_idx = [0, 5,4,3, 6,0,2, 7,0,1]             # where is the code in the ccw_dir
    counter_shifted_dir = [0, 6,9,8, 3,0,7, 2,1,4] # opposite code plus one in ccw
    dir_dx = [0, -1,0,+1, -1,0,+1, -1,0,1]         # code translated to shift in x-axis
    dir_dy = [0, +1,+1,+1, 0,0,0,  -1,-1,-1]       # code translated to shift in y-axis
    #
    # find first bro in the ccw direction starting from the direction
    # from which we have come to this position
    test_dir = counter_shifted_dir[last_forward_dir]
    #print(f"starting pos [{cx},{cy}], forward dir code {last_forward_dir}, thus examine code {test_dir}")
    nx = cx+dir_dx[test_dir]
    ny = cy+dir_dy[test_dir]
    while not (is_edge_pixel(image,nx,ny) and image[ny,nx] != 0):
        #print(f"  not contour at [{nx},{ny}], examined dir code {test_dir}")
        test_dir = ccw_dir[ (dir_idx[test_dir]+1)%8 ]
        nx = cx+dir_dx[test_dir]
        ny = cy+dir_dy[test_dir]
    #print(f"  happy at [{nx},{ny}], examined dir code {test_dir}")
    return nx,ny,test_dir

def trace_contour(image, max_iters, offset_x = 0, offset_y = 0):
    sy = 0
    sx = np.where(image[0] != 0)[0][0]
    last_forward_dir = 1
    #
    x_coords = [int(sx+offset_x)]
    y_coords = [int(sy+offset_y)]
    x,y,last_forward_dir = find_contour_neighbors(image, sx,sy,last_forward_dir)
    cnt = 1
    while not (x == sx and y == sy) and cnt < max_iters:
        x_coords.append(int(x+offset_x))
        y_coords.append(int(y+offset_y))
        x,y,last_forward_dir = find_contour_neighbors(image, x,y,last_forward_dir)
        cnt += 1
    #
    return x_coords,y_coords

def get_polygons_from_binary_mask(sam_result, at_least_of_this_size = 3, only_biggest=False):
    labels = measure.regionprops( measure.label(sam_result,connectivity=1) )
    x_contours = []
    y_contours = []
    sizes = []
    for obj in labels:
        if obj.num_pixels >= at_least_of_this_size:
            x_coords,y_coords = trace_contour(obj.image, obj.num_pixels, obj.bbox[1],obj.bbox[0])
            x_contours.append(x_coords)
            y_contours.append(y_coords)
            sizes.append(obj.num_pixels)
    if only_biggest:
        max_size_pos = np.array(sizes).argmax()
        x_contours = [x_contours[max_size_pos]]
        y_contours = [y_contours[max_size_pos]]
    return x_contours,y_contours
globals()['is_edge_pixel'] = is_edge_pixel
globals()['find_contour_neighbors'] = find_contour_neighbors
globals()['trace_contour'] = trace_contour
globals()['get_polygons_from_binary_mask'] = get_polygons_from_binary_mask

network -- [SERVICE-0] {"task":"f4d45f0e-0308-48f8-926d-acb3f71bda32","requestType":"EXECUTE","inputs":{},"script":"task.update(\u0027start\u0027)\r\nimport numpy as np\r\nfrom skimage import measure\r\nmeasure.label(np.ones((10, 10)), connectivity\u003d1)\r\nimport torch\r\nimport sys\r\nimport os\r\nos.chdir(r\u0027C:\\Fiji\\Fiji.app\\appose_x86_64\\envs\\efficientvit_sam_env\\efficientvit\u0027)\r\nfrom multiprocessing import shared_memory\r\ntask.update(\u0027import sam\u0027)\r\nfrom efficientvit.models.efficientvit import EfficientViTSam, efficientvit_sam_l0\r\nfrom efficientvit.models.efficientvit.sam import EfficientViTSamPredictor\r\ntask.update(\u0027imported\u0027)\r\n\r\nmodel \u003d efficientvit_sam_l0().cpu().eval()\r\neps \u003d 1e-6\r\nfor m in model.modules():\r\n  if isinstance(m, (torch.nn.GroupNorm, torch.nn.LayerNorm, torch.nn.modules.batchnorm._BatchNorm)):\r\n    if eps is not None:\r\n      m.eps \u003d eps\r\nf_name \u003d os.path.realpath(os.path.expanduser(r\u0027C:\\Fiji\\Fiji.app\\appose_x86_64\\envs\\efficientvit_sam_env\\efficientvit\\weights\\l0.pt\u0027))\r\nweight \u003d torch.load(f_name, map_location\u003d\u0027cpu\u0027)\r\nif \"state_dict\" in weight:\r\n  weight \u003d weight[\"state_dict\"]\r\nmodel.load_state_dict(weight)\r\npredictor \u003d EfficientViTSamPredictor(model)\r\ntask.update(\u0027created predictor\u0027)\r\nglobals()[\u0027shared_memory\u0027] \u003d shared_memory\r\nglobals()[\u0027measure\u0027] \u003d measure\r\nglobals()[\u0027np\u0027] \u003d np\r\nglobals()[\u0027torch\u0027] \u003d torch\r\nglobals()[\u0027predictor\u0027] \u003d predictor\r\ndef is_edge_pixel(image, cx,cy):\r\n    # assuming image[cy,cx] !\u003d 0\r\n    h,w \u003d image.shape\r\n    if cx \u003c 0 or cx \u003e\u003d w or cy \u003c 0 or cy \u003e\u003d h:\r\n        return False\r\n    # NB: cx,cy are valid coords\r\n    return cy \u003d\u003d 0 or image[cy-1,cx] \u003d\u003d 0 or cx \u003d\u003d 0 or image[cy,cx-1] \u003d\u003d 0 or cx \u003d\u003d w-1 or image[cy,cx+1] \u003d\u003d 0 or cy \u003d\u003d h-1 or image[cy+1,cx] \u003d\u003d 0\r\n\r\ndef find_contour_neighbors(image, cx,cy, last_forward_dir):\r\n    ccw_dir \u003d [8,9,6,3,2,1,4,7] # \"numpad directions\"\r\n    # so, directions are coded, and numbers 1-4,6-9 are used,\r\n    # let\u0027s use them as indices to the arrays below:\r\n    dir_idx \u003d [0, 5,4,3, 6,0,2, 7,0,1]             # where is the code in the ccw_dir\r\n    counter_shifted_dir \u003d [0, 6,9,8, 3,0,7, 2,1,4] # opposite code plus one in ccw\r\n    dir_dx \u003d [0, -1,0,+1, -1,0,+1, -1,0,1]         # code translated to shift in x-axis\r\n    dir_dy \u003d [0, +1,+1,+1, 0,0,0,  -1,-1,-1]       # code translated to shift in y-axis\r\n    #\r\n    # find first bro in the ccw direction starting from the direction\r\n    # from which we have come to this position\r\n    test_dir \u003d counter_shifted_dir[last_forward_dir]\r\n    #print(f\"starting pos [{cx},{cy}], forward dir code {last_forward_dir}, thus examine code {test_dir}\")\r\n    nx \u003d cx+dir_dx[test_dir]\r\n    ny \u003d cy+dir_dy[test_dir]\r\n    while not (is_edge_pixel(image,nx,ny) and image[ny,nx] !\u003d 0):\r\n        #print(f\"  not contour at [{nx},{ny}], examined dir code {test_dir}\")\r\n        test_dir \u003d ccw_dir[ (dir_idx[test_dir]+1)%8 ]\r\n        nx \u003d cx+dir_dx[test_dir]\r\n        ny \u003d cy+dir_dy[test_dir]\r\n    #print(f\"  happy at [{nx},{ny}], examined dir code {test_dir}\")\r\n    return nx,ny,test_dir\r\n\r\ndef trace_contour(image, max_iters, offset_x \u003d 0, offset_y \u003d 0):\r\n    sy \u003d 0\r\n    sx \u003d np.where(image[0] !\u003d 0)[0][0]\r\n    last_forward_dir \u003d 1\r\n    #\r\n    x_coords \u003d [int(sx+offset_x)]\r\n    y_coords \u003d [int(sy+offset_y)]\r\n    x,y,last_forward_dir \u003d find_contour_neighbors(image, sx,sy,last_forward_dir)\r\n    cnt \u003d 1\r\n    while not (x \u003d\u003d sx and y \u003d\u003d sy) and cnt \u003c max_iters:\r\n        x_coords.append(int(x+offset_x))\r\n        y_coords.append(int(y+offset_y))\r\n        x,y,last_forward_dir \u003d find_contour_neighbors(image, x,y,last_forward_dir)\r\n        cnt +\u003d 1\r\n    #\r\n    return x_coords,y_coords\r\n\r\ndef get_polygons_from_binary_mask(sam_result, at_least_of_this_size \u003d 3, only_biggest\u003dFalse):\r\n    labels \u003d measure.regionprops( measure.label(sam_result,connectivity\u003d1) )\r\n    x_contours \u003d []\r\n    y_contours \u003d []\r\n    sizes \u003d []\r\n    for obj in labels:\r\n        if obj.num_pixels \u003e\u003d at_least_of_this_size:\r\n            x_coords,y_coords \u003d trace_contour(obj.image, obj.num_pixels, obj.bbox[1],obj.bbox[0])\r\n            x_contours.append(x_coords)\r\n            y_contours.append(y_coords)\r\n            sizes.append(obj.num_pixels)\r\n    if only_biggest:\r\n        max_size_pos \u003d np.array(sizes).argmax()\r\n        x_contours \u003d [x_contours[max_size_pos]]\r\n        y_contours \u003d [y_contours[max_size_pos]]\r\n    return x_contours,y_contours\r\nglobals()[\u0027is_edge_pixel\u0027] \u003d is_edge_pixel\r\nglobals()[\u0027find_contour_neighbors\u0027] \u003d find_contour_neighbors\r\nglobals()[\u0027trace_contour\u0027] \u003d trace_contour\r\nglobals()[\u0027get_polygons_from_binary_mask\u0027] \u003d get_polygons_from_binary_mask\r\n"}
network -- [SERVICE-0] {"task": "f4d45f0e-0308-48f8-926d-acb3f71bda32", "responseType": "LAUNCH"}
network -- [SERVICE-0] {"task": "f4d45f0e-0308-48f8-926d-acb3f71bda32", "responseType": "UPDATE", "message": "start"}
network -- [SERVICE-0] {"task": "f4d45f0e-0308-48f8-926d-acb3f71bda32", "responseType": "UPDATE", "message": "import sam"}
network -- [SERVICE-0] {"task": "f4d45f0e-0308-48f8-926d-acb3f71bda32", "responseType": "UPDATE", "message": "imported"}
network -- [SERVICE-0] {"task": "f4d45f0e-0308-48f8-926d-acb3f71bda32", "responseType": "UPDATE", "message": "created predictor"}
network -- [SERVICE-0] {"task": "f4d45f0e-0308-48f8-926d-acb3f71bda32", "responseType": "COMPLETION", "outputs": {}}
Exception in thread "Thread-17" java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
	at com.sun.jna.platform.win32.Kernel32.<clinit>(Kernel32.java:44)
	at io.bioimage.modelrunner.tensor.shm.SharedMemoryArrayWin.<init>(SharedMemoryArrayWin.java:164)
	at io.bioimage.modelrunner.tensor.shm.SharedMemoryArrayWin.<init>(SharedMemoryArrayWin.java:134)
	at io.bioimage.modelrunner.tensor.shm.SharedMemoryArray.buildMemorySegmentForImage(SharedMemoryArray.java:136)
	at ai.nets.samj.EfficientViTSamJ.createEfficientSAMInputSHM(EfficientViTSamJ.java:756)
	at ai.nets.samj.EfficientViTSamJ.sendImgLib2AsNp(EfficientViTSamJ.java:568)
	at ai.nets.samj.EfficientViTSamJ.addImage(EfficientViTSamJ.java:349)
	at ai.nets.samj.EfficientViTSamJ.initializeSam(EfficientViTSamJ.java:225)
	at ai.nets.samj.communication.model.EfficientViTSAML0.<init>(EfficientViTSAML0.java:137)
	at ai.nets.samj.communication.model.EfficientViTSAML0.instantiate(EfficientViTSAML0.java:104)
	at ai.nets.samj.gui.SAMJDialog.lambda$actionPerformed$6(SAMJDialog.java:401)
	at java.lang.Thread.run(Thread.java:750)
`

**Comment by carlosuc3m** [comment]
Hello @ofrag, it seems that the plugin was not correctly installed in you computer Please check if the `jars` folder contains the two following JAR files:
* jna-5.13.0.jar
* jna-platform-5.13.0.jar

If not please update the plugin again. If it still does not work, and the JARs are not present in the `jars` folder, download both clicking in the following links and put the JAR files in their corresponding folder.

* https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
* https://mvnrepository.com/artifact/net.java.dev.jna/jna-platform/5.13.0

**Comment by ofrag** [comment]
Thanks @carlosuc3m 

This indeed solved the issue.
for some reason I had jna-3.2.7 installed, even after deleting it and reinstalling SAMJ. 
When I downloaded it directly from the link you pointed above, everything works smoothly. 
Thanks for making it available !

**Comment by carlosuc3m** [comment]
Happy its working! Try to always have your fiji updated when you are installing a new plugin!!

**Comment by carlosuc3m** [comment]
Thanks a lot for your feedback @kwolbachia !!
Where you able to solve it?

**Comment by kwolbachia** [comment]
Yes sorry! Adding manually the jna-5.13.0.jar provided fixed it and now it works like a charm. This is a great plugin thanks for it!

**Comment by ctrueden** [comment]
@ofrag @kwolbachia What other update sites do you have enabled? Out of the box, Fiji ships with jna-5.13.0.jar, not jna-3.2.7.jar. It is possible some other update site is still serving an outdated version of the JNA library.

**Comment by ctrueden** [comment]
I did a scan through all update sites served on sites.imagej.net, and the only one that ever served jna-3.2.7.jar (or any jna-3.x version) is DeepImageJ.

My next questions are:

1. If you run _Help > Update..._, does it bring in the newer jna?
2. If you uncheck the DeepImageJ update site in the Manage Update Sites dialog, Apply and Close, complete the update, then restart Fiji, does jna update to 5.13.0? Or stay at 3.2.7?

**Comment by kwolbachia** [comment]
Hi @ctrueden ,
I checked from the updater and my jna-3.2.7 is coming from https://fiji.sc/~schindelin/ffmpeg-plugins/ 
and indeed when I uncheck it the updater bring the newer one!

**Comment by ofrag** [comment]
following up on @kwolbachia , I confirm that: 
- uncheck ffmpeg (DeepImageJ unchecked, SAMJ checked): jna is updated to 5.13.0
- with DeepImageJ and SAMJ checked , ffmpeg unchecked : jna is still in version 5.13.0

**Comment by xulman** [comment]
I am afraid I would not tell you anything new, still pardon me please to note that one can have several Fiji**s** around.

I usually start with vanilla fresh Fiji, after unpacking it, I rename it e.g. to `Fiji-SAMJ.app`, and only then go for update sites and adding stuff (SAMJ here) into that particular Fiji. That way I tend to have several specialized and slim Fiji**s**, in contrast to fat one Fiji. That's my way of fighting .jar files clashes among various update sites. But I understand that it complicates work life (in several aspects).

**Comment by ctrueden** [comment]
Ahh, right, the FFMPEG update site. Forgot about that one, but this is not the first time that the jna version skew from there has caused trouble. Glad you were able to track it down.

I'm going to close this issue, since it's not a problem with SAMJ. I filed an issue at fiji/fiji#344 about the unfortunate state of the FFMPEG update site.
